try:
    from mmexofast.version import __version__
except ImportError:
    # version.py is generated by setuptools-scm at build/install time, so it is
    # absent in a fresh clone that has not been built or installed. Do not
    # hardcode a real-looking number here: it would go stale silently.
    __version__ = "0.0.0.dev0"

# Import classes
from mmexofast.classifier import AnomalyClassifier

# Re-exported so `mmexofast.DATA_PATH` keeps working; defined in config.py
# rather than duplicated here. DATA_PATH is the packaged data and is always
# present; SAMPLE_DATA_PATH is None for an installed package.
from mmexofast.config import (
    DATA_PATH,
    MODULE_PATH,
    PACKAGE_DATA_PATH,
    SAMPLE_DATA_PATH,
)
from mmexofast.dc18 import fetch_light_curves as fetch_dc18_light_curves
from mmexofast.gridsearches import (
    AnomalyFinderGridSearch,
    EventFinderGridSearch,
    ParallaxGridSearch,
)
from mmexofast.mmexofast import (
    MMEXOFASTFitter,
    OutputConfig,
    WorkflowStep,
    fit,
)
from mmexofast.results import (
    AllFitResults,
    FitRecord,
    GridSearchResult,
    MMEXOFASTFitResults,
)

__all__ = [
    "EventFinderGridSearch",
    "AnomalyFinderGridSearch",
    "ParallaxGridSearch",
    "MMEXOFASTFitResults",
    "FitRecord",
    "AllFitResults",
    "GridSearchResult",
    "MMEXOFASTFitter",
    "WorkflowStep",
    "OutputConfig",
    "fit",
    "AnomalyClassifier",
    "BellTemplateFitter",
    "fetch_dc18_light_curves",
    "MODULE_PATH",
    "PACKAGE_DATA_PATH",
    "DATA_PATH",
    "SAMPLE_DATA_PATH",
]
